import wx

GROUPS_INITIAL_VALUE = 4 
MEMBERS_INITIAL_VALUE = 12 

HIGHLIGHT_COLOR = wx.SystemSettings.GetColour(wx.SYS_COLOUR_HIGHLIGHT)
BACKGROUND_COLOR = wx.SystemSettings.GetColour(wx.SYS_COLOUR_WINDOW)

EVT_FORCE_RERENDER = wx.NewEventType()
EVT_FORCE_RERENDER_BINDER = wx.PyEventBinder(EVT_FORCE_RERENDER)